stages:
  - sync

sync:
  stage: sync
  variables:
    # Skip host key verification prompt
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    GIT_AUTHOR_NAME: "Innovation Upstream CI Bot"
    GIT_AUTHOR_EMAIL: "zach+ci@innovationupstream.com"
    GIT_COMMITTER_NAME: "Innovation Upstream CI Bot"
    GIT_COMMITTER_EMAIL: "zach+ci@innovationupstream.com"
    GIT_STRATEGY: clone
  image:
    name: nixos/nix
  before_script:
    - nix-channel --update
    - nix-env -iA nixpkgs.git nixpkgs.openssh
    - \[ -d ~/.ssh \] || mkdir ~/.ssh
    - |-
      cat <<EOT >> ~/.ssh/config
      Host github.com-apeswap
        Hostname github.com
        IdentityFile=$APESWAP_SSH_KEY_PRIVATE
      Host gitlab-iu
        Hostname gitlab.innovationup.stream
        IdentityFile=$APESWAP_SSH_KEY_PRIVATE
      EOT
    - chmod 0600 $APESWAP_SSH_KEY_PRIVATE
    - git config pull.rebase false
    - git config pull.ff false
  script:
    - export LAST_COMMIT_IU_MAIN=$(git log -n 1 --pretty=format:"%H")
    - git remote get-url origin-upstream || git remote add origin-upstream git@github.com-apeswap:ApeSwapFinance/apeswap-dex.git
    - git remote set-url origin git@gitlab-iu:apeswap/apeswap-frontend.git
    - git checkout origin-upstream/main
    - git pull origin-upstream main
    - export LAST_COMMIT_UPSTREAM_MAIN=$(git log -n 1 --pretty=format:"%H")
    - git switch -c main-downstream-$LAST_COMMIT_UPSTREAM_MAIN
    - \[ "$LAST_COMMIT_UPSTREAM_MAIN" = "$LAST_COMMIT_IU_MAIN" \] || git push -u origin main-downstream -o merge_request.create -o merge_request.target=main-iu
  rules:
    - if: '($CI_PIPELINE_SOURCE == "schedule" && $JOB_TYPE == "sync")'
      when: on_success
