name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
